spring:
  application:
    name: products-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: com.mysql.jdbc.Driver
    open-in-view: false
    generate-ddl: true
    show-sql: true
  datasource:
    url: "jdbc:mysql://localhost:3306/test"
    username: root
    password: mysql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}

server:
  port: 0

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug